-- Expande o cadastro de integrantes para suportar o modulo administrativo de usuarios.

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'INTEGRANTE'
          AND column_name = 'DE_ALTERACAO'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'INTEGRANTE'
          AND column_name = 'DT_ALTERACAO'
    ) THEN
        EXECUTE 'ALTER TABLE "INTEGRANTE" RENAME COLUMN "DE_ALTERACAO" TO "DT_ALTERACAO"';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'INTEGRANTE'
          AND column_name = 'id'
          AND is_identity = 'NO'
    ) THEN
        BEGIN
            EXECUTE 'ALTER TABLE "INTEGRANTE" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
        EXCEPTION
            WHEN others THEN
                NULL;
        END;
    END IF;
END $$;

ALTER TABLE "INTEGRANTE" ADD COLUMN IF NOT EXISTS "NOME_USUARIO" VARCHAR(255);
ALTER TABLE "INTEGRANTE" ADD COLUMN IF NOT EXISTS "SENHA" VARCHAR(255);

UPDATE "INTEGRANTE"
SET "NOME_USUARIO" = COALESCE("NOME_USUARIO", LOWER(REPLACE("NOME", ' ', '.'))),
    "DT_ALTERACAO" = COALESCE("DT_ALTERACAO", CURRENT_TIMESTAMP);
