-- Suporte a redefinicao de senha e historico de reutilizacao.

ALTER TABLE "INTEGRANTE" ADD COLUMN IF NOT EXISTS "RESET_TOKEN_HASH" VARCHAR(255);
ALTER TABLE "INTEGRANTE" ADD COLUMN IF NOT EXISTS "RESET_TOKEN_EXPIRA_EM" TIMESTAMP;
ALTER TABLE "INTEGRANTE" ADD COLUMN IF NOT EXISTS "SENHA_ANTERIOR_1" VARCHAR(255);
ALTER TABLE "INTEGRANTE" ADD COLUMN IF NOT EXISTS "SENHA_ANTERIOR_2" VARCHAR(255);
ALTER TABLE "INTEGRANTE" ADD COLUMN IF NOT EXISTS "SENHA_ANTERIOR_3" VARCHAR(255);
